CREATE TABLE IF NOT EXISTS FD_HISTORY
(
    PATH      VARCHAR PRIMARY KEY NOT NULL,
    FILE_NAME VARCHAR             NOT NULL,
    URL       VARCHAR             NOT NULL,
    SIZE      BIGINT              NOT NULL,
    DATE      TIMESTAMP           NOT NULL
);

CREATE TABLE IF NOT EXISTS GALLERY_CACHE
(
    URL       VARCHAR PRIMARY KEY NOT NULL,
    RESOURCES VARBINARY           NOT NULL
);
